# Generated by Django 3.1.7 on 2021-03-01 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinder_app.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(validators=[tinder_app.validator.validate_date])),
                ('counter_swipes', models.IntegerField(default=0)),
                ('block_disable', models.DateField(default=None)),
                ('distance_look', models.IntegerField(default=-1)),
                ('cords', models.CharField(max_length=200)),
                ('last_cords_update', models.DateField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_allowed_swipes', models.IntegerField()),
                ('allowed_distance', models.IntegerField()),
                ('group_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_like', models.BooleanField(default=False)),
                ('user2_like', models.BooleanField(default=False)),
                ('user1_like_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_like_key', to=settings.AUTH_USER_MODEL)),
                ('user2_like_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_like_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_dislike_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_dislike_key', to=settings.AUTH_USER_MODEL)),
                ('user2_dislike_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_dislike_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_app.usergroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_app.photo'),
        ),
    ]
