# Generated by Django 3.1.7 on 2021-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_disable',
            field=models.DateField(default=None, null=True),
        ),
    ]
