# Generated by Django 3.1.7 on 2021-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0005_auto_20210305_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_disable',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_cords_update',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
