# Generated by Django 3.1.7 on 2021-03-10 09:09

from django.db import migrations, models
import django.db.models.deletion
import user_app.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_allowed_swipes', models.IntegerField()),
                ('allowed_distance', models.IntegerField()),
                ('group_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(validators=[user_app.validator.validate_date])),
                ('counter_swipes', models.IntegerField(default=0)),
                ('block_disable', models.DateField(blank=True, default=None, null=True)),
                ('distance_look', models.IntegerField(default=-1)),
                ('cords', models.CharField(blank=True, max_length=200, null=True)),
                ('last_cords_update', models.DateField(blank=True, default=None, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.usergroup')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
